version: '3'

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

volumes:
    dbdata:

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 3306:3306
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  rundeck:
    image: rundeck/rundeck:4.2.1
    container_name: rundeck
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 4440:4440
    links:
      - mysql
    environment:
        RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
        RUNDECK_DATABASE_USERNAME: rundeck
        RUNDECK_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
        RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
        RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL}
        RUNDECK_SERVER_FORWARDED: true
    volumes:
      - $PWD/rundeck/config:/home/rundeck/server/config
    depends_on:
      - mysql
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks:
      - web
      - internal
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - rundeck
